//! TokenTransfer — decoded ERC-20 / ERC-721 / ERC-1155 transfer events.

use crate::{Address, BlockHeight, Hash, LogIndex, Wei};
use serde::{Deserialize, Serialize};

/// Token standard. Drives how `token_id` and `amount` are interpreted.
#[derive(Debug, Copy, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TokenStandard {
    /// Fungible — `amount` carries the value, `token_id` is None.
    Erc20,
    /// Non-fungible — `token_id` carries the NFT id, `amount` = 1.
    Erc721,
    /// Multi-token — both `token_id` and `amount` populated.
    Erc1155,
}

impl TokenStandard {
    /// String representation as stored in `token_transfers.standard`
    /// (varchar(12)).
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Erc20 => "erc20",
            Self::Erc721 => "erc721",
            Self::Erc1155 => "erc1155",
        }
    }
}

/// Decoded token transfer materialised from `logs`. Surrogate `id` PK is
/// generated by PG (`bigint generated always as identity`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TokenTransfer {
    /// PG-assigned surrogate. None when staging an insert.
    pub id: Option<i64>,
    /// Block this transfer was logged in.
    pub block_height: BlockHeight,
    /// Tx that emitted the transfer.
    pub tx_hash: Hash,
    /// Block-wide log index.
    pub log_index: LogIndex,
    /// Token contract address.
    pub contract: Address,
    /// Standard.
    pub standard: TokenStandard,
    /// Sender.
    pub from_addr: Address,
    /// Receiver.
    pub to_addr: Address,
    /// NFT id. None for ERC-20.
    pub token_id: Option<Wei>,
    /// Transferred amount (1 for ERC-721).
    pub amount: Wei,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn standard_serializes_lowercase() {
        assert_eq!(
            serde_json::to_string(&TokenStandard::Erc20).unwrap(),
            "\"erc20\""
        );
        assert_eq!(
            serde_json::to_string(&TokenStandard::Erc721).unwrap(),
            "\"erc721\""
        );
        assert_eq!(
            serde_json::to_string(&TokenStandard::Erc1155).unwrap(),
            "\"erc1155\""
        );
    }
}
